package:
  name: wrf-python
  version: "0.0.1"

source:
  git_url: git@github.com:NCAR/wrf-python.git
  git_rev: WRF_Workshop_2016

build:
  number: 5
  detect_binary_files_with_prefix: true

requirements:
  build:
    - numpy x.x
    - gcc
    - python
    - libgcc 4.8.5

  run:
    - numpy x.x
    - python
    - wrapt 
    - libgcc 4.8.5
    - xarray

test:
  requires:
    - nose
  imports:
    - wrf 
  #commands:
    #- cd $SRC_DIR/src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log


