
# For the version to work, the patch in ncl_reference needs to be applied
# to the installed conda-build.  Otherwise, it needs to be set manually until
# continuum can release a fix.
package:
  name: wrf-python
  version: 1.0a3

source:
  git_url: git@github.com:NCAR/wrf-python.git

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - numpy x.x
    - wrapt
    - m2w64-toolchain # [win]
    - gcc # [unix]
    - libgcc # [unix]
    - python
    
  run:
    - numpy x.x
    - python
    - wrapt 
    - m2w64-toolchain # [win]
    - libgcc # [unix]
    - xarray

test:
  requires:
    - nose
  imports:
    - wrf 
  #commands:
    #- cd $SRC_DIR/src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log


