package:
  name: wrf-python
  version: "0.0.1"

source:
  git_url: https://github.com/NCAR/wrf-python.git
  git_rev: WRF_Workshop_2016

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - numpy x.x
    - gcc
    - python

  run:
    - numpy x.x
    - python
    - wrapt 

test:
  requires:
    - nose
  imports:
    - wrf 
  #commands:
    #- cd $SRC_DIR/src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log


